### ISSUE TITLE
Error in extracted script.txt

### ISSUE THREAD

**Issue by diddpro** [denikson/COM3D2.i18nEx#3]
Hello.
First, Thank you for your work.

I found some error in error in some of extracted script.txt
For example 
ai_sya_02150a.txt

@stopvoice maid=0@eval exp="tf['痕種類'] = '精液'"@eval exp="tf['痕場所'] = '秘部'"@MotionScript file="sex_ran3p_osae_seijyoui" label=*射精中*L0|@face maid=0 name=まぶたギュ@face maid=0 name=エロ羞恥２ wait=1500@faceblend maid=0 name=頬３涙０ひぁ、やっ、うぐ、ぁあああああっ！　お、お客様のおちんちんで、うぅ……こんなに、中出し……あぁ、おまんこ溢れちゃう……	
@stopvoice maid=0@eval exp="tf['痕種類'] = '精液'"@eval exp="tf['痕場所'] = '秘部'"@MotionScript file="sex_ran3p_osae_seijyoui" label=*射精中*L1|@face maid=0 name=エロ痛み２@face maid=0 name=興奮射精後２ wait=1500@faceblend maid=0 name=頬３涙０はぐぅううう、んんんっ～～～～～！　うく、あぁん……ご主人様じゃないおちんちんで……おまんこ、イカされて……あぁ、せーえき、いっぱい……	

Some script parts was extracted. I searched "stop" keyword in all script.txt files.
5801 hits in 510 files (total 33494 files)

And can you add "copy to clipboard" function?
It is useful with off-line translator.

**Comment by ghorsington** [comment]
Fixed (at least temporarily) in 2bedb4f28.
