### ISSUE TITLE
Translated text from i18nEx being translated again by XUnity.AutoTranslator

### ISSUE THREAD

**Issue by Bigstrong-ZTJ** [denikson/COM3D2.i18nEx#8]
Hi!

I am using the i18nEx tool to translate my COM3D2 game into Chinese. In the meantime, I also try to use the [XUnity.AutoTranslator](https://github.com/bbepis/XUnity.AutoTranslator) to translate parts of the game that i18nEx does not translate. However, I noticed that the AutoTranslator still translate the entire game including translating the manual translations again. This means that my prepackaged Chinese translations in i18nEx are translated again by AutoTranslator and thus messing up the translations. 

I raised the same issue in the XUnity.AutoTranslator repository and @gravydevsupreme offered a potential solution to this problem. Details can be found [here](https://github.com/bbepis/XUnity.AutoTranslator/issues/215#issuecomment-914638624). This problem can probably be solved by letting i18nEx append a Mongolian vowel separator on texts it has translated, and thus the AutoTranslator could pick up this special character and skip those texts while performing the automated translations. 

Sadly, as I don't have sufficient programming skills to do this, I will have to kindly ask if you would like to implement this new feature in i18nEx. Or, is there any other ways that I can fix this problem? Anyways, I would like to thank you for making this handy tool and appreciate any help regarding this issue.

**Comment by ghorsington** [comment]
Greetings!

Thanks for the report! i18nEx 1.5.0 should now be able to signal to XUAT when i18nEx has translated the strings. In such cases XUAT should preserve both the original JP translation and the i18nEx translation. If i18nEx has not found any translations, XUAT should pick it up as usual.

This was preliminary tested on story text and noted to be working. As such, I'm closing this issue. However, if you still have problems, feel free to comment here again with a precise description of the issue and I'll reopen the ticket.
